# Rename to build dev version
# This is dev version
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "je_auto_control_dev"
version = "0.0.130"
authors = [
    { name = "JE-Chen", email = "jechenmailman@gmail.com" },
]
description = "GUI Automation Framework"
requires-python = ">=3.10"
license-files = ["LICENSE"]
dependencies = [
    "je_open_cv",
    "pillow",
    "pyobjc-core;platform_system=='Darwin'",
    "pyobjc;platform_system=='Darwin'",
    "python-Xlib;platform_system=='Linux'",
    "mss"
]
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Development Status :: 2 - Pre-Alpha",
    "Environment :: Win32 (MS Windows)",
    "Environment :: MacOS X",
    "Environment :: X11 Applications",
    "Operating System :: OS Independent"
]

[project.urls]
Homepage = "https://github.com/Intergration-Automation-Testing/AutoControl"
Documentation = "https://autocontrol.readthedocs.io/en/latest/"
Code = "https://github.com/Intergration-Automation-Testing/AutoControl"

[project.readme]
file = "README.md"
content-type = "text/markdown"

[tool.setuptools.packages]
find = { namespaces = false }

[project.optional-dependencies]
gui = ["PySide6==6.10.0", "qt-material"]
